<Project>
  <PropertyGroup>
    <LangVersion>12.0</LangVersion>
    <Nullable>enable</Nullable>
    <TreatWarningsAsErrors>false</TreatWarningsAsErrors>
  </PropertyGroup>

  <PropertyGroup>
    <Authors>WeaveLLM Contributors</Authors>
    <PackageLicenseExpression>MIT</PackageLicenseExpression>
    <PackageProjectUrl>https://github.com/harshil-sh/WeaveLLM</PackageProjectUrl>
    <RepositoryUrl>https://github.com/harshil-sh/WeaveLLM</RepositoryUrl>
    <RepositoryType>git</RepositoryType>
    <PackageReadmeFile>NUGET_README.md</PackageReadmeFile>
    <PackageIcon>Icon.jpg</PackageIcon>
  </PropertyGroup>
</Project>
