#nullable enable
namespace WeaveLLM.Core.Models;

/// <summary>The role of a message participant in a chat conversation.</summary>
public enum Role
{
    /// <summary>A system-level instruction that primes model behavior.</summary>
    System,
    /// <summary>Input from the human user.</summary>
    User,
    /// <summary>A reply generated by the assistant/model.</summary>
    Assistant,
    /// <summary>The result of a tool invocation.</summary>
    Tool
}

/// <summary>
/// An immutable, strongly-typed chat message. Use the static factory methods to construct instances.
/// </summary>
public sealed record Message
{
    /// <summary>The role of the sender.</summary>
    public required Role Role { get; init; }

    /// <summary>The text content of the message.</summary>
    public required string Content { get; init; }

    /// <summary>
    /// The tool call identifier this message responds to.
    /// Populated only when <see cref="Role"/> is <see cref="Role.Tool"/>.
    /// </summary>
    public string? ToolCallId { get; init; }

    /// <summary>
    /// The name of the tool that produced this message.
    /// Populated only when <see cref="Role"/> is <see cref="Role.Tool"/>.
    /// </summary>
    public string? ToolName { get; init; }

    /// <summary>Creates a system-prompt message.</summary>
    public static Message System(string content) =>
        new() { Role = Role.System, Content = content };

    /// <summary>Creates a user-turn message.</summary>
    public static Message User(string content) =>
        new() { Role = Role.User, Content = content };

    /// <summary>Creates an assistant-turn message.</summary>
    public static Message Assistant(string content) =>
        new() { Role = Role.Assistant, Content = content };

    /// <summary>Creates a tool-result message linking back to the originating call.</summary>
    public static Message Tool(string content, string toolCallId, string? toolName = null) =>
        new() { Role = Role.Tool, Content = content, ToolCallId = toolCallId, ToolName = toolName };
}
